### ISSUE TITLE
Issue with Running format_tokyo247.py due to MAT File Structure

### ISSUE THREAD

**Issue by SeunghanYu** [gmberton/datasets_vg#10]
Hello @ga1i13o @gmberton !

I recently downloaded the Tokyo 247 dataset and the corresponding MAT file using a link provided by the authors of NetVLAD for running **format_tokyo247.py**. Initially, the MAT file was named **dbfnames.mat**, so I renamed it to **tokyo247.mat** as expected by the script. However, upon executing **format_tokyo247.py**, I encountered an error.

Upon inspecting the contents of the MAT file I downloaded, I found it structured as follows:

    ['__header__']: bytes (76)
    ['__version__']: '1.0'
    ['__globals__']: list (0)
    ['dbfnames']: ndarray(object) (1, 75984)

Moreover, the internal structure seemed to be in the format:
['dbfnames'][0][0] = ['~/work/exp/Shibuya_2014/Shibuya_mid/db_gsv/03814/381426.780_3946120.387/VIfhhHgWyU5FW26SNHrzGQ_012_000']
['dbfnames'][0][1] = ['~/work/exp/Shibuya_2014/Shibuya_mid/db_gsv/03814/381426.780_3946120.387/VIfhhHgWyU5FW26SNHrzGQ_012_030']

It appears that the structure of the MAT file I received differs significantly from what **format_tokyo247.py** expects.
Could you advise if the correct **tokyo247.mat** file for the VPR-datasets-downloader-main is available somewhere, or if there is a specific version of the MAT file that I should be using?

**Comment by gmberton** [comment]
Hi, can you try with this tokyo247.mat file [tokyo247.zip](https://github.com/gmberton/VPR-datasets-downloader/files/14808006/tokyo247.zip)? You just need to extract the zip.

**Comment by SeunghanYu** [comment]
Thank you for your reply!
tokyo247.mat file successfully works!!
