### ISSUE TITLE
Pitt30k

### ISSUE THREAD

**Issue by yzxyzxyzxyzxyzx** [gmberton/datasets_vg#13]
please,where to dawnload datasets/pitts30k/raw_data,please give me a website_links
Thank you,thank you

**Comment by gmberton** [comment]
Hi, I can't give you a link to the dataset, you need to ask to the authors of NetVLAD

**Comment by HUSTNO1WXY** [comment]
Have you got the Pitt30k dataset? I sent authors the e-mail but got no response.
