### ISSUE TITLE
pitts250k format failed

### ISSUE THREAD

**Issue by aipanpan123** [gmberton/datasets_vg#14]
i get error like this:
![image](https://github.com/gmberton/VPR-datasets-downloader/assets/106948604/8d87a346-a4cf-460b-90bc-b0814ccaf618)

my file like this:
![image](https://github.com/gmberton/VPR-datasets-downloader/assets/106948604/0fd5e3b1-43ad-4fa3-b9b1-f2700f87f612)

i find some .mat in groundtruth
![image](https://github.com/gmberton/VPR-datasets-downloader/assets/106948604/dfd76845-de20-4b75-b77f-2c030faba68c)

what is happened? pitts250k has no pitts250k_train.mat?
thanks!

**Comment by jarvisyjw** [comment]
You missed a folder in the original data which is called a dataset, it contains files like "pitts250k_train.mat".
![image](https://github.com/gmberton/VPR-datasets-downloader/assets/75066365/818a4fa4-8148-4e62-9c64-697f4b4a37c2)

**Comment by jarvisyjw** [comment]
I think you need to check again and download the missing parts.

**Comment by aipanpan123** [comment]
yes！thank you very much!
