### ISSUE TITLE
How to get msls-challenge?

### ISSUE THREAD

**Issue by STSTERANDMOMO** [gmberton/datasets_vg#15]
In many benchmarks,msls-challenge dataset is needed.How to get it?

**Comment by jarvisyjw** [comment]
I think it is an online challenge, you can check [here](https://codalab.lisn.upsaclay.fr/competitions/865) for more info.

**Comment by STSTERANDMOMO** [comment]
> I think it is an online challenge, you can check [here](https://codalab.lisn.upsaclay.fr/competitions/865) for more info.

But the benchmark don't provide how to handle the msls-challenge dataset. I don't konw how to congnize the dataset.

**Comment by gmberton** [comment]
Hi, the challenge dataset does not have public labels and therefore we can't process it in the same way that we do with any other dataset, so we preferred not to include it in this list. Furthermore, when testing to submit the solution on the challenge's server, the test should be perform city by city (i.e. do retrieval for Athens's queries only within Athens's database), which would make it even more complex (and less consistent with the rest of the benchmark)

**Comment by lv162** [comment]
How can I get the msls-challenge data set? The literature on vpr that I read has test verification results on this data set.
