### ISSUE TITLE
MSLS mismatch in number of queries

### ISSUE THREAD

**Issue by Shubodh** [gmberton/datasets_vg#18]
Thank you for the wonderful repo, Berton.

Regarding Mapillary SLS or MSLS dataset in regards to standard VPR benchmarking:

Standard VPR methods like MixVPR, SALAD use MSLS_Val for testing their methods. More importantly, they don't seem to be using all the query images of SF and CPH but only a small subset of those. For reference, see 

1. [mixVPR](https://github.com/amaralibey/MixVPR/issues/5#issuecomment-1438784599)
2. [SALAD/GSV-Cities](https://github.com/serizba/salad/issues/3#issuecomment-1880567424)

[GSV-Cities](https://github.com/amaralibey/gsv-cities/tree/main/datasets/msls_val) actually provides nice npy files to directly extract ground truth and calculate recall values.

city | num of ref / num of query (original num of queries)
SF | 6315 / 242   (4525)   
CPH | 12556 /  498  (6595)   

However, In your code,  

1. We are using all queries (4525 and 6595). Therefore we might need to do some preprocessing to rewrite the .csv files from original msls dataset folders.
2. Additionally, I think we shouldn't be combining both the cities, i.e. the reference (and query) sets during evaluation must be maintained separately. They should essentially be treated as different datasets, but in your case, the way you would reorganize the dataset is such that it puts reference of both the cities in one folder and likewise for query.
3. Also after downloading dataset from MSLS official site, we get various splits. We need to manually look into it and rewrite it such that all the cities are in one parent folder. Perhaps this too can be made part of your preprocessing code.

I am documenting here for now, if you agree with my points, I shall submit a PR very soon.

Thank you.
Shubodh

**Comment by Shubodh** [comment]
I have written 2 scripts to solve this issue and give it in a manner required for VPR. However the image names don't follow your convention. I can rewrite and submit a PR here if needed, else the below scripts would be sufficient for VPR. Below repo also has GT code calculation.


https://github.com/AnyLoc/Revisit-Anything/tree/main/dataloaders/msls_data_clean

**Comment by gmberton** [comment]
Hi @Shubodh, thank you for your issue and sorry for the delay.

For the way this benchmark is constructed (and how I designed every VPR code for all my repos), I didn't take into account the fact that one dataset might have multiple databases, although this is usually done for evaluating MSLS (as you mention in your point 2), so I'm not planning to update the code to resolve issue 2 as it would lead to a lot of breaking changes throughout all my VPR codebases.

Regarding your point 1, you're right on that, as the original MSLS code uses one query per sequence. Now I could fix this issue, although I believe this would lead to even more confusion: right now there are 2 versions of MSLS val used in VPR papers (ours and the original one), but if I reduce the number of queries (while keeping the databases merged) the number of versions will become 3, making comparisons between different papers even more complex, so I'm not planning to reduce the number of queries.

So practically, I think it would either make sense to fix both issues 1 and 2 (which would lead to breaking changes) or neither of them.

Regarding point 3, I'm not sure I understand what you mean. Do you refer to splits as in day/night, train/val, or splits by city?

**Comment by Shubodh** [comment]
Hi @gmberton 

I understand, and it might lead to breaking changes if we try to fix these issues because of the way your benchmark is constructed. We can keep it as it is if you feel that's the best. So those who want to test for below number of queries can use [my repo](https://github.com/AnyLoc/Revisit-Anything/tree/main/dataloaders/msls_data_clean).

city | num of ref / num of query (original num of queries)
SF | 6315 / 242 (4525)
CPH | 12556 / 498 (6595)

Thanks for your time!
