### ISSUE TITLE
why test set only?

### ISSUE THREAD

**Issue by GyoungTaeChae** [gmberton/datasets_vg#19]
Hello 

first, i really appreciate  your curated work . 
as a beginner of this area , it will help a lot .
i want to know most of dataset is test-set-only. why? 
it's for code for convinient download. but i wonder why it gives only test dataset. 

thank you

**Comment by gmberton** [comment]
Hi, most of these datasets do not have a train set. Usually we train on a different dataset (e.g. Pitts30k) and test on the other ones (e.g. Tokyo 24/7)
