### ISSUE TITLE
about msls

### ISSUE THREAD

**Issue by GyoungTaeChae** [gmberton/datasets_vg#20]
hello, i succeeded formatting every datasets except mapillary.
i downloaded via the link you provided and unzip those things.

in `VPR-datasets-downloader/datasets/mapillary_sls` 
when  i typed tree -L 2 , it output is like :

![image](https://github.com/user-attachments/assets/f1b62e39-e32e-4fb5-b52b-047c1b958ce6)

it is the right file directory structure to run the code?
i can't  make it although i read the code 

thankyou

**Comment by Shubodh** [comment]
Hey, you can check the issue i opened, where i clearly explain what the problem is: https://github.com/gmberton/VPR-datasets-downloader/issues/18 . I shall share code to fix it soon, keep an eye out on that issue.

**Comment by GyoungTaeChae** [comment]
> Hey, you can check the issue i opened, where i clearly explain what the problem is: #18 . I shall share code to fix it soon, keep an eye out on that issue.

thankyou!

**Comment by Shubodh** [comment]
Hello @GyoungTaeChae 
I have not pushed a PR on current repo yet but have released 2 data cleaning scripts in my repo which will give MSLS dataset in a manner required for VPR. It was very difficult to work with this dataset and was taking a lot of time everytime I set it up, hence I created these. You can take a look and let me know if that's helpful.

https://github.com/AnyLoc/Revisit-Anything/tree/main/dataloaders/msls_data_clean

**Comment by lv162** [comment]
Hello
I want to know how to use your code to process the msls dataset. After processing with your code, aren't the msls-test dataset and the msls-val dataset the same? Also, what is the msls-challenge dataset mentioned in the literature?
I am looking forward to your answer，thank you.

**Comment by gmberton** [comment]
The dataset before formatting should look like this, by just unzipping the files provided by Mapillary
![asdf](https://github.com/user-attachments/assets/878f9890-375e-40a2-84e3-012d8ee002ef)
