### ISSUE TITLE
Bug in format_pitts250k?

### ISSUE THREAD

**Issue by xjh19971** [gmberton/datasets_vg#6]
In format_pittes250k.py L55-56
```
copy_images(f"{dataset_folder}/images/{dataset}/queries", q_images, q_utms)
copy_images(os.path.join(dataset_folder, 'images', dataset, 'queries'), q_images, q_utms)
```
Seems like these two lines are duplicated and cause an error.

**Comment by gmberton** [comment]
Right, I removed the first line, it should work properly now.
Thank you for the issue :-)
