### ISSUE TITLE
Project website is down

### ISSUE THREAD

**Issue by Leerw** [gmberton/datasets_vg#7]
Hi, the project website mentioned in the README https://deep-vg-bench.herokuapp.com/ is down. Would you please check it ?

**Comment by gmberton** [comment]
Thank you for notifying us. The free plan from heroku has been removed, and so the website is now offline.
We are currently investigating other hosting plans.
Anyway, on the website there were a subset of the results from the paper, so you can find everything on the paper (and supplementary).
